<?php

require __DIR__ . '/../vendor/autoload.php';

//\Anferov\QrCode\Generator\QrCode::png('здесь был вася', 'test.png', 'L', 4, 2);

//same as above but outputs file directly into browser (with appr. header etc.)
//all other settings are default
//WARNING! it should be FIRST and ONLY output generated by script, otherwise
//rest of output will land inside PNG binary, breaking it for sure
\Anferov\QrCode\Generator\QrCode::png('здесь был вася');

//show benchmark
\Anferov\QrCode\Generator\QrTools::timeBenchmark();

//rebuild cache
\Anferov\QrCode\Generator\QrTools::buildCache();

//code generated in text mode - as a binary table
//then displayed out as HTML using Unicode block building chars :)
$tab = $qr->encode('PHP QR Code :)');
\Anferov\QrCode\Generator\QrSpec::debug($tab, true);
